//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEST_DE_STOCK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GEST_DE_STOCKEntities : DbContext
    {
        public GEST_DE_STOCKEntities()
            : base("name=GEST_DE_STOCKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Commande> Commande { get; set; }
        public virtual DbSet<Employe> Employe { get; set; }
        public virtual DbSet<Fournisseur> Fournisseur { get; set; }
        public virtual DbSet<Ligne_commande> Ligne_commande { get; set; }
        public virtual DbSet<Ligne_livraison> Ligne_livraison { get; set; }
        public virtual DbSet<Ligne_vente> Ligne_vente { get; set; }
        public virtual DbSet<Livraison> Livraison { get; set; }
        public virtual DbSet<Produit> Produit { get; set; }
        public virtual DbSet<Vente> Vente { get; set; }
    }
}
