//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEST_DE_STOCK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ligne_vente
    {
        public int ID_ligne_vente { get; set; }
        public int ID_vente { get; set; }
        public int ID_produit { get; set; }
        public int Quantite_vente { get; set; }
        public int Prix_produit { get; set; }
    
        public virtual Produit Produit { get; set; }
        public virtual Vente Vente { get; set; }
    }
}
