//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEST_DE_STOCK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ligne_livraison
    {
        public int ID_ligne_livraison { get; set; }
        public int ID_livraison { get; set; }
        public int ID_ligne_commande { get; set; }
        public int Qunatite_livraison { get; set; }
    
        public virtual Ligne_commande Ligne_commande { get; set; }
        public virtual Livraison Livraison { get; set; }
    }
}
