//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEST_DE_STOCK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vente()
        {
            this.Ligne_vente = new HashSet<Ligne_vente>();
        }
    
        public int ID_vente { get; set; }
        public int ID_client { get; set; }
        public string ID_employe { get; set; }
        public System.DateTime Date_vente { get; set; }
        public System.TimeSpan Heure_vente { get; set; }
        public int Prix_vente { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employe Employe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ligne_vente> Ligne_vente { get; set; }
    }
}
